apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-chatbot-rolling-demo-25041003
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-chatbot-rolling-demo-25041003
  name: test-chatbot-rolling-demo-25041003
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-chatbot-rolling-demo-25041003
